### ISSUE TITLE
Eliminate go requirement for ref-arch

### ISSUE THREAD

**Issue by richarddli** [datawire/build-aux#2]
We're now using `build-aux` in the reference architecture. It would be really nice to eliminate the use of Go for the ref arch use case. According to @LukeShu it's used to determine your arch/env but not much else. Not sure how hard this would be, but the alternative would need to support Mac/Linux as well.

**Comment by LukeShu** [comment]
This is fixed in this repo.  It still needs to be merged in pro-ref-arch#27. Tracking can happen in pro-ref-arch#11.
